package trabalho2.dcc171;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class mainJanela extends javax.swing.JFrame {

    private ProtocoloDAO dao;
    private ProtocoloTableModel protocoloModel;

    public mainJanela() {
               
        try {
            protocoloModel = new ProtocoloTableModel();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver não disponível", "Sem driver!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível conectar ao banco de dados!", "Sem banco!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
            System.exit(2);
        }
        try {
            dao = new ProtocoloDAOJDBC();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível criar o DAO!", "Erro no DAO!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
        //jTable1.setAutoCreateRowSorter(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnUtilizar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(protocoloModel);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnUtilizar.setText("Utilizar");
        btnUtilizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Setor");

        jLabel2.setText("Protocolo");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jButton1.setText("Adicionar Mult.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("até");

        jLabel4.setText("Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUtilizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemover))
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtilizar)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover)
                    .addComponent(jButton1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            Protocolo newProtocol = new Protocolo();
            newProtocol.setSetor(jTextField1.getText());
            newProtocol.setProtocolo(Integer.parseInt(jTextField2.getText()));
            dao.insertProtocolVazio(newProtocol);
            jTextField1.setText("");
            jTextField2.setText("");
            jTable1.updateUI();
            jTextField1.requestFocus(); 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            Protocolo newProtocol = new Protocolo();
            int i = jTable1.getSelectedRow();
            newProtocol.setSetor((String) jTable1.getModel().getValueAt(i, 1));
            newProtocol.setLastUsed((Timestamp) jTable1.getModel().getValueAt(i, 2));
            newProtocol.setProtocolo((int) jTable1.getModel().getValueAt(i, 0));
            dao.removeProtocol(newProtocol);
            jTextField1.setText("");
            jTextField2.setText("");
            jTable1.updateUI();
            jTextField1.requestFocus();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnUtilizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilizarActionPerformed
        try {
            Protocolo newProtocol = new Protocolo();
            int i = jTable1.getSelectedRow();
            newProtocol.setSetor((String) jTable1.getModel().getValueAt(i, 1));
            newProtocol.setLastUsed((Timestamp) jTable1.getModel().getValueAt(i, 2));
            newProtocol.setProtocolo((int) jTable1.getModel().getValueAt(i, 0));
            dao.updateProtocol(newProtocol);
            jTextField1.setText("");
            jTextField2.setText("");
            jTable1.updateUI();
            jTextField1.requestFocus();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUtilizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int i;
            int j = Integer.parseInt(jTextField3.getText());
            for(i= Integer.parseInt(jTextField2.getText());i<j;i++)
            {
            Protocolo newProtocol = new Protocolo();
            newProtocol.setSetor(jTextField1.getText());
            newProtocol.setProtocolo(i);
            dao.insertProtocolVazio(newProtocol);
            }
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTable1.updateUI();
            jTextField1.requestFocus();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro salvar os dados", "Erro na inserção!", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(mainJanela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2) == null)
        {
            btnUtilizar.setEnabled(true);
        }
        else
        {
            btnUtilizar.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJanela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJanela().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnUtilizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
